/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './../app/__root'
import { Route as PageImport } from './../app/page'
import { Route as HomePageImport } from './../app/home/page'
import { Route as ContactPageImport } from './../app/contact/page'

// Create/Update Routes

const PageRoute = PageImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomePageRoute = HomePageImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const ContactPageRoute = ContactPageImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageImport
      parentRoute: typeof rootRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactPageImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomePageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/contact': typeof ContactPageRoute
  '/home': typeof HomePageRoute
}

export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/contact': typeof ContactPageRoute
  '/home': typeof HomePageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof PageRoute
  '/contact/': typeof ContactPageRoute
  '/home/': typeof HomePageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/home'
  id: '__root__' | '/' | '/contact/' | '/home/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  ContactPageRoute: typeof ContactPageRoute
  HomePageRoute: typeof HomePageRoute
}

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  ContactPageRoute: ContactPageRoute,
  HomePageRoute: HomePageRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contact/",
        "/home/"
      ]
    },
    "/": {
      "filePath": "page.tsx"
    },
    "/contact/": {
      "filePath": "contact/page.tsx"
    },
    "/home/": {
      "filePath": "home/page.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
