/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PostIdImport } from './routes/post/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const PostIndexLazyImport = createFileRoute('/post/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PostIndexLazyRoute = PostIndexLazyImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/post/index.lazy').then((d) => d.Route))

const PostIdRoute = PostIdImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdImport
      parentRoute: typeof rootRoute
    }
    '/post/': {
      id: '/post/'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/post/$id': typeof PostIdRoute
  '/post': typeof PostIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/post/$id': typeof PostIdRoute
  '/post': typeof PostIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/post/$id': typeof PostIdRoute
  '/post/': typeof PostIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/post/$id' | '/post'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/post/$id' | '/post'
  id: '__root__' | '/' | '/post/$id' | '/post/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PostIdRoute: typeof PostIdRoute
  PostIndexLazyRoute: typeof PostIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PostIdRoute: PostIdRoute,
  PostIndexLazyRoute: PostIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/post/$id",
        "/post/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/post/$id": {
      "filePath": "post/$id.tsx"
    },
    "/post/": {
      "filePath": "post/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
