/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './__root'
import { Route as RouteTreeGenImport } from './routeTree.gen'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./index.lazy').then((d) => d.Route))

const RouteTreeGenRoute = RouteTreeGenImport.update({
  id: '/routeTree/gen',
  path: '/routeTree/gen',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/routeTree/gen': {
      id: '/routeTree/gen'
      path: '/routeTree/gen'
      fullPath: '/routeTree/gen'
      preLoaderRoute: typeof RouteTreeGenImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/routeTree/gen': typeof RouteTreeGenRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/routeTree/gen': typeof RouteTreeGenRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/routeTree/gen': typeof RouteTreeGenRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/routeTree/gen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/routeTree/gen'
  id: '__root__' | '/' | '/routeTree/gen'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RouteTreeGenRoute: typeof RouteTreeGenRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RouteTreeGenRoute: RouteTreeGenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/routeTree/gen"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/routeTree/gen": {
      "filePath": "routeTree.gen.ts"
    }
  }
}
ROUTE_MANIFEST_END */
